### PR TITLE
Add STARTTLS to LDAP connection

### PR DESCRIPTION
**Pull request by jdow**

### CODE REVIEW

**Comment by gene1wood** [comment]
Switching the review request for Julien from his github.com/mozilla org owner user (moz-jvehent) to his daily driver user (jvehent). I also granted jvehent collaborator access to the repo (a prerequisite for providing a review)

**Review by jvehent — APPROVED** [review]
this is a one line code change so I guess it's alright if it gets the job done :man_shrugging: 

do you need me to push a new version to pypi? (damn, it's been 4 years since the last update)

**Comment by jdow** [comment]
Probably good to push it to pypi. I was thinking about this more and I wonder if anyone else is using this lib that might not want the forced STARTTLS, so more correctly it should probably an option in the config... but this one liner is perfect for our usage at Mozilla, and I've already updated it where we use it.

**Comment by jvehent** [comment]
updated upstream, even though I seriously doubt anyone else is using it
https://pypi.org/project/libnfldap/

**Pull request merged**
